#define BASIC_TRIE_ADDRESS_SIZE 4 // in bytes
#define BASIC_TRIE_VALUE_SIZE 1 // in bytes
#define BASIC_TRIE_FREQUENCY_SIZE 4 // in bytes
#define BASIC_TRIE_N_CHILDREN_SIZE 4 // in bytes


#define COMPACT_TRIE_VALUE_SIZE 1
#define COMPACT_TRIE_FREQUENCY_SIZE 4
#define COMPACT_TRIE_CHILDREN_OFFSET_SIZE 4
#define COMPACT_TRIE_N_CHILDREN_SIZE 1
#define COMPACT_TRIE_NODE_SIZE 10
